version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "chown -R node:node /app && npm run dev -- --host"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/notesdb
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    command: sh -c "chown -R node:node /app && npm install && npm run dev"

volumes:
  pgdata:
  frontend_node_modules:
  backend_node_modules:
